spring.application.name=real-time_collaborative_editor

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/editor
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

custom.jwt_secret=${JWT_SECRET}
custom.jwt.expiration.access=900000
custom.jwt.expiration.refresh=604800000
custom.jwt.expiration.websocket=120000

custom.history.size=50

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html